# This file is used with the cli-talky-talk gem
# Some of the words in segments are misspelled intentionally to make them sound more accurate when pronounced.
options:
  voice:
    whitelist:
    blacklist:
      - Trinoids
      - Good News
      - Bad News
      - Bubbles
      - Veena
      - Boing
      - Pipe Organ
      - Albert
      - Tessa
      - Bahh
      - Deranged
      - Hysterical
      - Whisper
      - Bells

segments:
  greetings:
    - ahoy
    - greeting
    - saalutations
    - waazame
    - bleep booop
    - exceslior
    - land hoe
    - hail
  
  names:
    - WHOAMI
    - Govna
    - captain
    - boss
    - cheef
    - over loard
    - dragon commander
    - your excellence
    - exhaulted one
  
  statuses:
    - all done here
    - works done
    - bingo!
    - hazaa
    - flip Yeah
    - get back to work
    - all systems go
  
